### PR TITLE
Transcribed earlier version of the Token Sale to MD.

### PR DESCRIPTION
**Pull request by mindshade**
- Added details and naming in general.
- Added the two step refund to separate Pre and Public sale.

### CODE REVIEW

**Comment by aroysbox** [comment]
Lets refer it as Token Sale instead of ICO

**Comment by mindshade** [comment]
@aroysbox Fixed replace to Token Sale.

**Comment by mindshade** [comment]
@ashisherc Please have a thorough look at this document when you are available and let me know if it corresponds with your thinking.

**Comment by aroysbox** [comment]
Maybe we can break it up into separate pages like get started guide so that it looks smaller and less complex :)

**Comment by mindshade** [comment]
@aroysbox Yes, breaking it up into more manageable pages is a good idea! Lets get this first version approved first and then I will break it up into sections?

**Comment by mindshade** [comment]
@aroysbox I have updated the strategy for concluding the sale, keeping the trustors involved, in case of unforeseen events forces us to freeze assets. This can now be done, supervised by four trustors.

**Pull request merged**
